from .comuna import Comuna
from .establecimiento import Establecimiento
from .ficha import Ficha
from .genero import Genero
from .movimiento_ficha import MovimientoFicha
from .pacientes import Paciente
from .pais import Pais
from .prevision import Prevision
from .profesion import Profesion
from .profesionales import Profesional
from .servicio_clinico import ServicioClinico
