# Generated by Django 4.1.13 on 2025-09-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0004_remove_ingresopaciente_diagnostico_ingreso_and_more'),
        ('usuarios', '0002_alter_usuariopersonalizado_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='comuna',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kardex.establecimiento', verbose_name='Establecimiento'),
        ),
    ]
