# Generated by Django 4.1.13 on 2025-09-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('address', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=15, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
    ]
