# Generated by Django 4.1.13 on 2025-09-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=200, verbose_name='Código de Comuna')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('rut2', models.CharField(max_length=100, verbose_name='R.U.T. Provisorio')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_mov', models.DateTimeField(verbose_name='Fecha de Movimiento')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrada')),
                ('observacion_entrada', models.TextField(blank=True, null=True, verbose_name='Observación de Entrada')),
                ('observacion_salida', models.TextField(blank=True, null=True, verbose_name='Observación de Salida')),
                ('usuario_entrega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que Entrega')),
                ('usuario_entrada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que Entrada')),
                ('status2', models.CharField(choices=[('ENTREGA', 'Entrgado'), ('RECIBIDO', 'Recibido')], default='EN ESPERA', max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Prevision',
                'verbose_name_plural': 'Previsiones',
            },
        ),
        migrations.CreateModel(
            name='ServicioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tiempo_horas', models.IntegerField(verbose_name='Tiempo en horas')),
                ('correo_jefe', models.EmailField(max_length=100, unique=True, verbose_name='Correo del jefe a cargo')),
                ('telefono', models.CharField(max_length=15, unique=True, verbose_name='Teléfono')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kardex.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Servicio Clínico',
                'verbose_name_plural': 'Servicios Clínicos',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('rut', models.CharField(max_length=100, unique=True, verbose_name='R.U.T.')),
                ('nombres', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=15, unique=True, verbose_name='Teléfono')),
                ('tipo_usuario', models.CharField(choices=[('MEDICO', 'Medico'), ('ENFERMERA', 'Enfermera'), ('ANESTESISTA', 'Anestesista'), ('MATRONA', 'Matrona'), ('ADMINISTRATIVO', 'Administrativo'), ('PROFESIONAL CLINICO', 'Profesional Clínico')], default='ADMINISTRATIVE', max_length=100, verbose_name='Tipo de Usuario')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kardex.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('rut', models.CharField(max_length=100, unique=True, verbose_name='R.U.T.')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, unique=True, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, unique=True, verbose_name='Apellido Materno')),
                ('rut_madre', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='R.U.T. Madre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('SOLTERO(A)', 'Soltero(a)'), ('CASADO(A)', 'Casado(a)'), ('DIVORCIADO(A)', 'Divorciado(a)'), ('VIUDO(A)', 'Viudo(a)'), ('CONVIVIENTE', 'Conviviente')], max_length=20, verbose_name='Estado Civil')),
                ('nombres_pabre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres del Padre')),
                ('nombres_madre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres de la Madre')),
                ('nombre_pareja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Pareja')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('numero_telefono1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono')),
                ('numero_telefono2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono 2')),
                ('fecha_movimiento', models.DateField(auto_now=True, verbose_name='Fecha de Movimiento')),
                ('pasaporte', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Pasaporte')),
                ('recien_nacido', models.BooleanField(default=False, verbose_name='Recién Nacido')),
                ('extranjero', models.BooleanField(default=False, verbose_name='Extranjero')),
                ('fallecido', models.BooleanField(default=False, verbose_name='Fallecido')),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('representante_legal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Representante Legal')),
                ('nombre_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Social')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.comuna', verbose_name='Comuna')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kardex.ficha', verbose_name='Ficha')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.prevision', verbose_name='Previsión')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
