# Generated by Django 4.1.13 on 2025-09-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kardex.ficha', verbose_name='Ficha'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='servicio_clinico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.servicioclinico', verbose_name='Servicio Clínico'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='ingresopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ingreso_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.ingresopaciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.comuna', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kardex.pais', verbose_name='País'),
        ),
    ]
