# Generated by Django 4.1.13 on 2025-09-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='pasaporte',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='rut_madre',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kardex.paciente', verbose_name='Paciente'),
        ),
    ]
