# Generated by Django 4.1.13 on 2025-09-26 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopaciente',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kardex.establecimiento', verbose_name='Establecimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresopaciente',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
    ]
