# Generated by Django 5.2.7 on 2025-10-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='pasivado',
            field=models.BooleanField(default=False, verbose_name='Pasivado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pasivado',
            field=models.BooleanField(default=False, verbose_name='Pasivado'),
        ),
    ]
