# Generated by Django 4.1.13 on 2025-09-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_ingresopaciente_establecimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresopaciente',
            name='diagnostico_ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresopaciente',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='ingresopaciente',
            name='fecha_egreso',
        ),
        migrations.RemoveField(
            model_name='ingresopaciente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresopaciente',
            name='motivo_ingreso',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_movimiento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='NIE'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rut_responsable_temporal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RUT Responsable Temporal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usar_rut_madre_como_responsable',
            field=models.BooleanField(default=False, verbose_name='Usar RUT de la madre como responsable'),
        ),
    ]
