# Generated by Django 5.2.7 on 2025-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_historicalpaciente_pasivado_paciente_pasivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='sin_telefono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sin_telefono',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='R.U.T.'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='R.U.T.'),
        ),
    ]
