# Generated by Django 4.1.13 on 2025-09-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0004_remove_ingresopaciente_diagnostico_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Rut'),
        ),
    ]
