# Generated by Django 5.2.7 on 2025-10-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0004_historicalpaciente_sin_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaciente',
            name='pasivado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pasivado',
        ),
        migrations.AddField(
            model_name='ficha',
            name='pasivado',
            field=models.BooleanField(default=False, verbose_name='Pasivado'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='pasivado',
            field=models.BooleanField(default=False, verbose_name='Pasivado'),
        ),
    ]
