# Generated by Django 5.2.7 on 2025-10-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0005_remove_historicalpaciente_pasivado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofesional',
            name='anexo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='anexo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='historicalprofesional',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='historicalprofesional',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
