# Generated by Django 4.1.13 on 2025-10-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0005_paciente_codigo_alter_paciente_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='fecha_mov',
        ),
    ]
