# Generated by Django 4.1.13 on 2025-10-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0006_remove_ficha_fecha_creacion_remove_ficha_fecha_mov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='ingreso_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.ingresopaciente', unique=True, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kardex.profesional', verbose_name='Profesional'),
        ),
    ]
