# Generated by Django 5.2.7 on 2025-10-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0006_historicalprofesional_anexo_profesional_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicioclinico',
            name='correo_jefe',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo del jefe a cargo'),
        ),
        migrations.AlterField(
            model_name='servicioclinico',
            name='correo_jefe',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo del jefe a cargo'),
        ),
    ]
