# Generated by Django 4.1.13 on 2025-10-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0007_alter_ficha_ingreso_paciente_alter_ficha_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='numero_ficha',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de Ficha'),
        ),
    ]
