# Generated by Django 4.1.13 on 2025-10-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0008_alter_ficha_numero_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='ingreso_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.ingresopaciente', verbose_name='Paciente'),
        ),
    ]
