# Generated by Django 5.2.7 on 2025-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0008_alter_historicalpaciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='numero_telefono1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasaporte'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_telefono1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasaporte'),
        ),
    ]
