# Generated by Django 5.2.7 on 2025-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0009_alter_historicalpaciente_numero_telefono1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='genero',
            field=models.CharField(choices=[('NO INFORMADO', 'No Informado'), ('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO BINARIO', 'No Binario'), ('GÉNERO FLUIDO', 'Género Fluido'), ('TRANSGÉNERO', 'Transgénero'), ('MUJER TRANS', 'Mujer Trans'), ('HOMBRE TRANS', 'Hombre Trans'), ('INTERSEX', 'Intersex'), ('AGÉNERO', 'Agénero'), ('PREFIERO NO DECIRLO', 'Prefiero no decirlo'), ('OTRO', 'Otro')], default='NO INFORMADO', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='historicalservicioclinico',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('NO INFORMADO', 'No Informado'), ('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO BINARIO', 'No Binario'), ('GÉNERO FLUIDO', 'Género Fluido'), ('TRANSGÉNERO', 'Transgénero'), ('MUJER TRANS', 'Mujer Trans'), ('HOMBRE TRANS', 'Hombre Trans'), ('INTERSEX', 'Intersex'), ('AGÉNERO', 'Agénero'), ('PREFIERO NO DECIRLO', 'Prefiero no decirlo'), ('OTRO', 'Otro')], default='NO INFORMADO', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='servicioclinico',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
