# Generated by Django 5.2.7 on 2025-10-21 20:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0010_alter_historicalpaciente_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUsuarioAnterior',
            fields=[
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('rut', models.CharField(db_index=True, max_length=100, verbose_name='R.U.T.')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('establecimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.establecimiento', verbose_name='Establecimiento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario Anterior',
                'verbose_name_plural': 'historical Usuarios Anteriores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UsuarioAnterior',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='R.U.T.')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_anteriores_establecimientos', to='kardex.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Usuario Anterior',
                'verbose_name_plural': 'Usuarios Anteriores',
            },
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='usuario_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.usuarioanterior', verbose_name='UsuarioAnterior'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_anteriores', to='kardex.usuarioanterior', verbose_name='UsuarioAnterior'),
        ),
    ]
