# Generated by Django 5.2.7 on 2025-10-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0010_historicalcomuna_historicalestablecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AlterUniqueTogether(
            name='ingresopaciente',
            unique_together={('paciente', 'establecimiento')},
        ),
    ]
