# Generated by Django 5.2.7 on 2025-10-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0011_historicalusuarioanterior_usuarioanterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuarioanterior',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarioanterior',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
