# Generated by Django 5.2.7 on 2025-10-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0011_historicalmovimientoficha_profesional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaciente',
            name='nie',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nie',
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='nip',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nip',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_respuesta',
            field=models.CharField(choices=[('ENTREGA', 'Entregado'), ('RECIBIDO', 'Recibido')], default='EN ESPERA', max_length=50, verbose_name='Estado de Respuesta'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='estado_civil',
            field=models.CharField(choices=[('NO INFORMADO', 'No Informado'), ('SOLTERO(A)', 'Soltero(a)'), ('CASADO(A)', 'Casado(a)'), ('DIVORCIADO(A)', 'Divorciado(a)'), ('VIUDO(A)', 'Viudo(a)'), ('CONVIVIENTE', 'Conviviente')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_respuesta',
            field=models.CharField(choices=[('ENTREGA', 'Entregado'), ('RECIBIDO', 'Recibido')], default='EN ESPERA', max_length=50, verbose_name='Estado de Respuesta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('NO INFORMADO', 'No Informado'), ('SOLTERO(A)', 'Soltero(a)'), ('CASADO(A)', 'Casado(a)'), ('DIVORCIADO(A)', 'Divorciado(a)'), ('VIUDO(A)', 'Viudo(a)'), ('CONVIVIENTE', 'Conviviente')], max_length=20, verbose_name='Estado Civil'),
        ),
    ]
