# Generated by Django 5.2.7 on 2025-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0012_alter_historicalusuarioanterior_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='alergico_a',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alergico a'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergico_a',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alergico a'),
        ),
    ]
