# Generated by Django 5.2.7 on 2025-10-12 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0012_remove_historicalpaciente_nie_remove_paciente_nie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='estado_respuesta',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='fecha_mov',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='observacion_entrada',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='observacion_salida',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='usuario_entrada',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='usuario_entrega',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='estado_respuesta',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='fecha_mov',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='observacion_entrada',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='observacion_salida',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='servicio_clinico',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='usuario_entrada',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='usuario_entrega',
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='estado_envio',
            field=models.CharField(choices=[('ENTREGA', 'Entregado'), ('RECIBIDO', 'Recibido')], default='EN ESPERA', max_length=50, verbose_name='Estado de Envío'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='estado_recepcion',
            field=models.CharField(choices=[('ENTREGA', 'Entregado'), ('RECIBIDO', 'Recibido')], default='EN ESPERA', max_length=50, verbose_name='Estado de Recepción'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='observacion_envio',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Envío'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='observacion_recepcion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Recepción'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Envío'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Recepción'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='estado_envio',
            field=models.CharField(choices=[('ENTREGA', 'Entregado'), ('RECIBIDO', 'Recibido')], default='EN ESPERA', max_length=50, verbose_name='Estado de Envío'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='estado_recepcion',
            field=models.CharField(choices=[('ENTREGA', 'Entregado'), ('RECIBIDO', 'Recibido')], default='EN ESPERA', max_length=50, verbose_name='Estado de Recepción'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='observacion_envio',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Envío'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='observacion_recepcion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Recepción'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_profesionales', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_profesionales', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='servicio_clinico_envio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='envios_desde_este_servicio', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Envío'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='servicio_clinico_recepcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_en_este_servicio', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Recepción'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
