# Generated by Django 5.2.7 on 2025-10-13 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0013_remove_historicalmovimientoficha_estado_respuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Envío'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Recepción'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_profesionales', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_profesionales', to='kardex.profesional', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='servicio_clinico_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_desde_este_servicio', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Envío'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='servicio_clinico_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_en_este_servicio', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Recepción'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
