# Generated by Django 5.2.7 on 2025-10-22 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0013_historicalpaciente_alergico_a_paciente_alergico_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.RemoveField(
            model_name='historicalgenero',
            name='history_user',
        ),
        migrations.AddField(
            model_name='ficha',
            name='fecha_creacion_anterior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='fecha_creacion_anterior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='numero_ficha_sistema',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='numero_ficha_tarjeta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Tarjeta'),
        ),
        migrations.AlterField(
            model_name='historicalficha',
            name='numero_ficha_sistema',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha'),
        ),
        migrations.AlterField(
            model_name='historicalficha',
            name='numero_ficha_tarjeta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Tarjeta'),
        ),
        migrations.AddConstraint(
            model_name='ficha',
            constraint=models.UniqueConstraint(fields=('numero_ficha_sistema', 'establecimiento'), name='unique_ficha_por_establecimiento'),
        ),
        migrations.DeleteModel(
            name='HistoricalGenero',
        ),
    ]
