# Generated by Django 5.2.7 on 2025-10-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0014_alter_historicalmovimientoficha_estado_envio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='ingreso_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kardex.ingresopaciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional Envio'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Envio'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Recepcion'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_profesionales', to='kardex.profesional', verbose_name='Profesional Envio'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_profesionales', to='kardex.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Envio'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Recepcion'),
        ),
    ]
