# Generated by Django 5.2.7 on 2025-10-24 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0014_delete_genero_remove_historicalgenero_history_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='estado_traspaso',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='fecha_traspaso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Traspaso'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='observacion_traspaso',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Traspaso'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional_traspaso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_traspaso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Traspaso'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_traspaso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='estado_traspaso',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='fecha_traspaso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='observacion_traspaso',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional_traspaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_traspaso_profesionales', to='kardex.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='servicio_clinico_traspaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspaso_en_este_servicio', to='kardex.servicioclinico', verbose_name='Servicio Clínico de Traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_traspaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_traspasados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Traspaso'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
    ]
