# Generated by Django 5.2.7 on 2025-10-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0015_historicalmovimientoficha_estado_traspaso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicioclinico',
            name='tiempo_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo en horas'),
        ),
        migrations.AlterField(
            model_name='servicioclinico',
            name='tiempo_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo en horas'),
        ),
    ]
