# Generated by Django 5.2.7 on 2025-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0016_alter_historicalservicioclinico_tiempo_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='estado',
            field=models.CharField(blank=True, default='SIN DATOS', max_length=50, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='estado',
            field=models.CharField(blank=True, default='SIN DATOS', max_length=50, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_traspaso',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_traspaso',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso'),
        ),
    ]
