# Generated by Django 5.2.7 on 2025-10-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0017_historicalmovimientoficha_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmovimientoficha',
            old_name='estado',
            new_name='estado_anterior',
        ),
        migrations.RenameField(
            model_name='movimientoficha',
            old_name='estado',
            new_name='estado_anterior',
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.profesional', verbose_name='Profesional Anterior'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_envio_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.usuarioanterior', verbose_name='Usuario Envio Anterior'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_recepcion_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.usuarioanterior', verbose_name='Usuario Recepcion Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_anterior_profesionales', to='kardex.profesional', verbose_name='Profesional Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_envio_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_anterior', to='kardex.usuarioanterior', verbose_name='Usuario Envio Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_recepcion_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_anterior', to='kardex.usuarioanterior', verbose_name='Usuario Recepcion Anterior'),
        ),
    ]
