# Generated by Django 5.2.7 on 2025-10-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0018_rename_estado_historicalmovimientoficha_estado_anterior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='historicalmovimientoficha',
            name='profesional_anterior',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='movimientoficha',
            name='profesional_anterior',
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='rut_anterior',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_fichas_establecimientos', to='kardex.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='rut_anterior',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior'),
        ),
    ]
