# Generated by Django 5.2.7 on 2025-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0019_remove_historicalmovimientoficha_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='rut_anterior_profesional',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Profesional'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='rut_anterior_profesional',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Profesional'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='rut_anterior',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='rut_anterior',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario'),
        ),
    ]
