# Generated by Django 5.2.7 on 2025-11-04 13:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0020_historicalmovimientoficha_rut_anterior_profesional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSector',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código del Sector')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color del Sector')),
                ('observacion', models.TextField(blank=True, choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('NARANJA', 'Naranja'), ('MORADO', 'Morado'), ('ROSA', 'Rosa'), ('MARRÓN', 'Marrón'), ('GRIS', 'Gris'), ('NEGRO', 'Negro'), ('CIAN', 'Cian'), ('MAGENTA', 'Magenta'), ('LIMA', 'Lima'), ('VERDE AZULADO', 'Verde azulado'), ('AZUL MARINO', 'Azul marino'), ('GRANATE', 'Granate'), ('OLIVA', 'Oliva'), ('DORADO', 'Dorado'), ('PLATEADO', 'Plateado'), ('BEIGE', 'Beige')], null=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comuna', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.comuna', verbose_name='Comuna')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sector',
                'verbose_name_plural': 'historical Sectores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima fecha de Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=8, verbose_name='Estado')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código del Sector')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color del Sector')),
                ('observacion', models.TextField(blank=True, choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('NARANJA', 'Naranja'), ('MORADO', 'Morado'), ('ROSA', 'Rosa'), ('MARRÓN', 'Marrón'), ('GRIS', 'Gris'), ('NEGRO', 'Negro'), ('CIAN', 'Cian'), ('MAGENTA', 'Magenta'), ('LIMA', 'Lima'), ('VERDE AZULADO', 'Verde azulado'), ('AZUL MARINO', 'Azul marino'), ('GRANATE', 'Granate'), ('OLIVA', 'Oliva'), ('DORADO', 'Dorado'), ('PLATEADO', 'Plateado'), ('BEIGE', 'Beige')], null=True, verbose_name='Observaciones')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_comuna', to='kardex.comuna', verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_sectores', to='kardex.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.sector', verbose_name='Sector'),
        ),
    ]
