# Generated by Django 5.2.7 on 2025-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0021_historicalsector_sector_ficha_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='pueblo_indigena',
            field=models.BooleanField(default=False, verbose_name='Pueblo Indigena'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pueblo_indigena',
            field=models.BooleanField(default=False, verbose_name='Pueblo Indigena'),
        ),
    ]
