# Generated by Django 5.2.7 on 2025-11-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0022_historicalpaciente_pueblo_indigena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsector',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='comuna',
        ),
        migrations.AddField(
            model_name='historicalsector',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kardex.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='sector',
            name='establecimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='sector_establecimiento', to='kardex.establecimiento', verbose_name='Establecimiento'),
            preserve_default=False,
        ),
    ]
