# Generated by Django 5.2.7 on 2025-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0023_remove_historicalsector_comuna_remove_sector_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='nip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='R.U.T.'),
        ),
        migrations.AlterField(
            model_name='historicalsector',
            name='color',
            field=models.CharField(blank=True, default='NO INFORMADO', max_length=100, null=True, verbose_name='Color del Sector'),
        ),
        migrations.AlterField(
            model_name='historicalservicioclinico',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='R.U.T.'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='color',
            field=models.CharField(blank=True, default='NO INFORMADO', max_length=100, null=True, verbose_name='Color del Sector'),
        ),
        migrations.AlterField(
            model_name='servicioclinico',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
